# Site settings
title: 个人博客
header-img: "http://oogbkd3ln.bkt.clouddn.com/green.jpg"
tagline: "cn"
description: "蔡军的博客"
baseurl: ""
url: "caijun_carr.github.io"

# About/contact
owner:
  name: " caijun"
  email: caijun_carr@163.com
  bio: "世界很大，做自己就好"

# Data
gavatar: http://oogbkd3ln.bkt.clouddn.com/caijun.jpg
favicon: http://oogbkd3ln.bkt.clouddn.com/favicon.png

douban_username:
twitter_username:
github_username:
facebook_username:
weibo_username:
zhihu_username:

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
gems: [jekyll-paginate]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "caijun"
      comments: true
      header-img: "http://oogbkd3ln.bkt.clouddn.com/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name :
  disqus :
      short_name :

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
